/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 08-feb-2018 02:59:59 p.m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `afp` CASCADE
;

DROP TABLE IF EXISTS `fondopo` CASCADE
;

DROP TABLE IF EXISTS `fondopv` CASCADE
;

DROP TABLE IF EXISTS `rendimientohistoricofondopo` CASCADE
;

DROP TABLE IF EXISTS `rendimientohistoricofondopv` CASCADE
;

DROP TABLE IF EXISTS `tipofondoPo` CASCADE
;

DROP TABLE IF EXISTS `tipofondopv` CASCADE
;

/* Create Tables */

CREATE TABLE `afp`
(
	`afpId` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NULL,
	CONSTRAINT `PK_AFP` PRIMARY KEY (`afpId` ASC)
)

;

CREATE TABLE `fondopo`
(
	`fondoPoId` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NULL,
	`fondo_id` INT NOT NULL,
	`id_tipoFondoPo` INT NULL,
	CONSTRAINT `PK_FONDOPO` PRIMARY KEY (`fondoPoId` ASC)
)

;

CREATE TABLE `fondopv`
(
	`fondoPvId` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(150) NULL,
	`fondo_id` INT NOT NULL,
	`id_tipoFondoPv` INT NULL,
	CONSTRAINT `PK_FONDOPV_AFP` PRIMARY KEY (`fondoPvId` ASC)
)

;

CREATE TABLE `rendimientohistoricofondopo`
(
	`rendimientoHistoricoFondoPoId` BIGINT NOT NULL AUTO_INCREMENT,
	`id_fondopo` INT NOT NULL,
	`fecha` DATE NULL,
	`porcentaje` DECIMAL(18,12) NULL,
	`valor` DECIMAL(18,12) NULL,
	CONSTRAINT `PK_HISTORICO_FONDOPO` PRIMARY KEY (`rendimientoHistoricoFondoPoId` ASC)
)

;

CREATE TABLE `rendimientohistoricofondopv`
(
	`rendimientoHistoricoPvId` BIGINT NOT NULL AUTO_INCREMENT,
	`id_fondopv` INT NOT NULL,
	`fecha` DATE NULL,
	`porcentaje` DECIMAL(18,12) NULL,
	`valor` DECIMAL(18,12) NULL,
	CONSTRAINT `PK_HISTORICO_FONDOPV` PRIMARY KEY (`rendimientoHistoricoPvId` ASC)
)

;

CREATE TABLE `tipofondoPo`
(
	`tipo_fondoPoId` INT NOT NULL,
	`nombre` VARCHAR(150) NULL,
	CONSTRAINT `PK_TIPOS_FONDOPO` PRIMARY KEY (`tipo_fondoPoId` ASC)
)

;

CREATE TABLE `tipofondopv`
(
	`tipoFondoPvId` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(150) NULL,
	CONSTRAINT `PK_TIPOS_FONDOSPV` PRIMARY KEY (`tipoFondoPvId` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `rendimientohistoricofondopo` 
 ADD CONSTRAINT `UK_FONDO_FECHA_PORCENTAJE_VALOR` UNIQUE (`id_fondopo` ASC, `fecha` ASC, `valor` ASC, `porcentaje` ASC)
;

ALTER TABLE `rendimientohistoricofondopv` 
 ADD CONSTRAINT `UK_FONDOPV_FECHA_PORCENTAJE_VALOR` UNIQUE (`id_fondopv` ASC, `fecha` ASC, `valor` ASC, `porcentaje` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `fondopo` 
 ADD CONSTRAINT `FK_FONDOPO_AFP`
	FOREIGN KEY (`fondo_id`) REFERENCES `afp` (`afpId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `fondopo` 
 ADD CONSTRAINT `FK_FONDOPO_TIPO_FONDOPO`
	FOREIGN KEY (`id_tipoFondoPo`) REFERENCES `tipofondoPo` (`tipo_fondoPoId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `fondopv` 
 ADD CONSTRAINT `FK_FONDOPV_AFP`
	FOREIGN KEY (`fondo_id`) REFERENCES `afp` (`afpId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `fondopv` 
 ADD CONSTRAINT `FK_FONDOPV_TIPO_FONDOPV`
	FOREIGN KEY (`id_tipoFondoPv`) REFERENCES `tipofondopv` (`tipoFondoPvId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `rendimientohistoricofondopo` 
 ADD CONSTRAINT `FK_RENDIMIENTO_HISTORICO_FONDOPO`
	FOREIGN KEY (`id_fondopo`) REFERENCES `fondopo` (`fondoPoId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `rendimientohistoricofondopv` 
 ADD CONSTRAINT `FK_RENDIMIENTO_HISTORICO_FONDOPV`
	FOREIGN KEY (`id_fondopv`) REFERENCES `fondopv` (`fondoPvId`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
